# Generated by Django 5.0.6 on 2024-07-04 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Timeapp", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
