# Generated by Django 5.0.6 on 2024-07-04 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Timeapp", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
    ]
